Create an example usage of GatorGrade
GatorEducator/gatorgrade-hello-world pull request #1
Opened 2022-05-04 15:35 UTC by laurennevill

# Sample Repository to Demonstrate GatorGrade

## Description

This PR contains changes made to the hello-gatorgrade repo that will serve as a demonstration of how to use GatorGrade. This PR contains a gatorgrade.yml file, some simple source code, and a sample reflection as well as a readme for the repo. 

## Type of Change

- [x] Feature
- [ ] Documentation
- [ ] Bug fix

## Contributors

- @laurennevill 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

2022-05-06 17:24 UTC, burgess01 submitted a review, later dismissed
This looks great to me, good job!

2022-05-06 17:52 UTC, ullrichd21 submitted a review, later dismissed
Looks perfect! Great job! 👍🏻 
<img src="https://media1.giphy.com/media/ely3apij36BJhoZ234/giphy-downsized-medium.gif"/>

2022-05-09 16:37 UTC, Michionlion requested changes
This looks awesome! Just one point of feedback.

2022-05-09 16:37 UTC, Michionlion commented on gatorgrade.yml
> +  ./script.sh
This line will cause GatorGrade to fail because `script.sh` is not a valid script. Could you remove this line?

2022-05-09 17:14 UTC, laurennevill commented on gatorgrade.yml
> +  ./script.sh
For sure! Thank you for the feedback

2022-05-09 18:38 UTC, Michionlion submitted a review, later dismissed
This looks great!

2022-05-09 20:07 UTC, noorbuchi submitted a review, later dismissed

2022-05-09 20:07 UTC, noorbuchi commented
Looks great!

2022-05-09 20:11 UTC, mariakimheinert requested changes
Hi @laurennevill! Thanks for producing this really useful sample assignment! I will be very helpful to future GatorGrade users 🙂  There are two minor issues in the `gatorgrade.yml` that should be fixed, but this PR should be good to go after these are resolved!

2022-05-09 20:11 UTC, mariakimheinert commented on gatorgrade.yml
> +- path/to:
Since `hello_world.py` is at the top level of the repository, `path/to` should not exist

2022-05-09 20:11 UTC, mariakimheinert commented on gatorgrade.yml
> +  - writing/reflection.md:
I believe this will not work since the `writing` directory is actually capitalized. So, either the actual `Writing` directory will need to be lowercased or this code will need to be uppercased (I vote for lowercasing the actual directory 😄).

2022-05-09 21:28 UTC, laurennevill commented on gatorgrade.yml
> +- path/to:
Oh thats a good point, thank you for catching that!

2022-05-09 21:29 UTC, laurennevill commented on gatorgrade.yml
> +  - writing/reflection.md:
I'll rename the directory now

2022-05-09 21:35 UTC, laurennevill commented on gatorgrade.yml
> +  - writing/reflection.md:
Hmm for some reason the repo is `writing` on my end but it won't allow me to commit/push that change to here?

2022-05-09 21:39 UTC, laurennevill commented on gatorgrade.yml
> +  - writing/reflection.md:
I figured it out and it should show as lowercase now!

2022-05-09 21:40 UTC, Michionlion commented on gatorgrade.yml
> +  - writing/reflection.md:
Are you on Windows? Directory naming is case-insensitive and so there isn't an easy way to ensure your directories are named correctly. [This](https://stackoverflow.com/a/36800417) stack overflow answer may help.

2022-05-09 21:44 UTC, Michionlion approved these changes
This looks good to me!

2022-05-09 21:46 UTC, laurennevill commented on gatorgrade.yml
> +  - writing/reflection.md:
I work on a Macbook and was able to correct it by opening my VSCode editor directly from GitHub and it seemed to work. Thank you for your suggestion!

2022-05-09 22:23 UTC, mariakimheinert approved these changes
Looks great, @laurennevill! Thank you for the revisions :shipit:

2022-05-10 14:23 UTC, noorbuchi approved these changes

2022-05-10 16:57 UTC, burgess01 approved these changes

2022-05-10 17:03 UTC, merged